CREATE TABLE [dbo].[COUNTRIES] (
    [COUNTRY_ID]   CHAR (2)     NOT NULL,
    [COUNTRY_NAME] VARCHAR (40) NULL,
    [REGION_ID]    INT          NULL,
    CONSTRAINT [COUNTRY_C_ID_PK] PRIMARY KEY CLUSTERED ([COUNTRY_ID] ASC),
    CONSTRAINT [COUNTR_REG_FK] FOREIGN KEY ([REGION_ID]) REFERENCES [dbo].[REGIONS] ([REGION_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [COUNTRY_C_ID_PKX]
    ON [dbo].[COUNTRIES]([COUNTRY_ID] ASC);

