CREATE TABLE [dbo].[DEPARTMENTS] (
    [DEPARTMENT_ID]   INT          NOT NULL,
    [DEPARTMENT_NAME] VARCHAR (30) NOT NULL,
    [MANAGER_ID]      INT          NULL,
    [LOCATION_ID]     INT          NULL,
    CONSTRAINT [DEPT_ID_PK] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC),
    CONSTRAINT [DEPT_LOC_FK] FOREIGN KEY ([LOCATION_ID]) REFERENCES [dbo].[LOCATIONS] ([LOCATION_ID]),
    CONSTRAINT [DEPT_MGR_FK] FOREIGN KEY ([MANAGER_ID]) REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
);


GO
CREATE NONCLUSTERED INDEX [DEPT_LOCATION_IX]
    ON [dbo].[DEPARTMENTS]([LOCATION_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [DEPT_ID_PKX]
    ON [dbo].[DEPARTMENTS]([DEPARTMENT_ID] ASC);

