CREATE TABLE [dbo].[EMPLOYEES] (
    [EMPLOYEE_ID]    INT            NOT NULL,
    [FIRST_NAME]     VARCHAR (20)   NULL,
    [LAST_NAME]      VARCHAR (25)   NOT NULL,
    [EMAIL]          VARCHAR (25)   NOT NULL,
    [PHONE_NUMBER]   VARCHAR (20)   NULL,
    [HIRE_DATE]      DATE           NOT NULL,
    [JOB_ID]         VARCHAR (10)   NOT NULL,
    [SALARY]         DECIMAL (8, 2) NULL,
    [COMMISSION_PCT] DECIMAL (2, 2) NULL,
    [MANAGER_ID]     INT            NULL,
    [DEPARTMENT_ID]  INT            NULL,
    CONSTRAINT [EMP_EMP_ID_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_ID] ASC),
    CONSTRAINT [EMP_SALARY_MIN] CHECK ([salary]>(0)),
    CONSTRAINT [EMP_DEPT_FK] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENTS] ([DEPARTMENT_ID]),
    CONSTRAINT [EMP_JOB_FK] FOREIGN KEY ([JOB_ID]) REFERENCES [dbo].[JOBS] ([JOB_ID]),
    CONSTRAINT [EMP_MANAGER_FK] FOREIGN KEY ([MANAGER_ID]) REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID]),
    CONSTRAINT [EMP_EMAIL_UK] UNIQUE NONCLUSTERED ([EMAIL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [EMP_DEPARTMENT_IX]
    ON [dbo].[EMPLOYEES]([DEPARTMENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [EMP_JOB_IX]
    ON [dbo].[EMPLOYEES]([JOB_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [EMP_MANAGER_IX]
    ON [dbo].[EMPLOYEES]([MANAGER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [EMP_NAME_IX]
    ON [dbo].[EMPLOYEES]([LAST_NAME] ASC, [FIRST_NAME] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EMP_EMP_ID_PKX]
    ON [dbo].[EMPLOYEES]([EMPLOYEE_ID] ASC);

