CREATE TABLE [dbo].[JOB_HISTORY] (
    [EMPLOYEE_ID]   INT          NOT NULL,
    [START_DATE]    DATE         NOT NULL,
    [END_DATE]      DATE         NOT NULL,
    [JOB_ID]        VARCHAR (10) NOT NULL,
    [DEPARTMENT_ID] INT          NULL,
    CONSTRAINT [JHIST_ID_DATE_PK] PRIMARY KEY CLUSTERED ([EMPLOYEE_ID] ASC, [START_DATE] ASC),
    CONSTRAINT [JHIST_DATE_CHECK] CHECK ([END_DATE]>[START_DATE]),
    CONSTRAINT [JHIST_DEPT_FK] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENTS] ([DEPARTMENT_ID]),
    CONSTRAINT [JHIST_EMP_FK] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID]),
    CONSTRAINT [JHIST_JOB_FK] FOREIGN KEY ([JOB_ID]) REFERENCES [dbo].[JOBS] ([JOB_ID])
);


GO
CREATE NONCLUSTERED INDEX [JHIST_JOB_IX]
    ON [dbo].[JOB_HISTORY]([JOB_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [JHIST_EMP_IX]
    ON [dbo].[JOB_HISTORY]([EMPLOYEE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [JHIST_DEPT_IX]
    ON [dbo].[JOB_HISTORY]([DEPARTMENT_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [JHIST_ID_DATE_PKX]
    ON [dbo].[JOB_HISTORY]([EMPLOYEE_ID] ASC, [START_DATE] ASC);

