CREATE TABLE [dbo].[REGIONS] (
    [REGION_ID]   INT          NOT NULL,
    [REGION_NAME] VARCHAR (25) NULL,
    CONSTRAINT [REG_ID_PK] PRIMARY KEY CLUSTERED ([REGION_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [REG_ID_PKX]
    ON [dbo].[REGIONS]([REGION_ID] ASC);

